[package]
name = "fl-store"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
fl-core = { path = "../core" }
redb.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
fl-core = { path = "../core", features = ["conformance"] }
